name: Terraform-plan
on: push
    
jobs:
      terraform-plan:
        name: Terraform Plan
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Terraform Plan
            run: |
              terraform init
              terraform fmt -recursive
              terraform validate
              terraform plan